<?php

/**
 * @file
 * Main file for the Etrade miscellaneous module, which containg logics for adding or alter node related functionality.
 * 
 * @ingroup etrade_misc
 */


function etrade_misc_node_presave($node){
	/*global $user;
	if($node->type == 'user_profile'){
		$user = user_load($user->uid);
		if(in_array('administrator', $user->roles) || in_array('Manager', $user->roles)) {
			return true;
		}
		else{
			if(in_array('authenticated user', $user->roles)){
				if(!empty($node->field_company_name[LANGUAGE_NONE]) && !empty($node->field_company_type[LANGUAGE_NONE]) && !empty($node->field_address_company[LANGUAGE_NONE]) && !empty($node->field_state[LANGUAGE_NONE]) && !empty($node->field_landline_no_of_company[LANGUAGE_NONE]) && !empty($node->field_tax_registration_no_[LANGUAGE_NONE]) && !empty($node->field_authorized_person[LANGUAGE_NONE]) && !empty($node->field_address_of_authorized_pers[LANGUAGE_NONE]) && !empty($node->field_phone_number[LANGUAGE_NONE]) && !empty($node->field_email_address[LANGUAGE_NONE]) && !empty($node->field_state[LANGUAGE_NONE][0]['city']) && !empty($node->field_state[LANGUAGE_NONE][0]['province']) && !empty($node->field_state[LANGUAGE_NONE][0]['country']) && !empty($node->field_state[LANGUAGE_NONE][0]['postal_code']) && (!empty($node->field_registration_certificate[LANGUAGE_NONE]) || !empty($node->field_address_proof_of_company[LANGUAGE_NONE]) || !empty($node->field_id_proof_of_authorized[LANGUAGE_NONE]))) {	
					$user->field_profile_status1[LANGUAGE_NONE][0]['value'] = 1;
					user_save($user);
					}
				else {
					$user->field_profile_status1[LANGUAGE_NONE][0]['value'] = 0;
					user_save($user);	
				}
			}
		}
	}*/
}

function etrade_misc_form_alter(&$form, &$form_state, $form_id) {	
	global $user;
	global $base_url;
	if($form_id == 'user_profile_node_form'){
		$userlink = $base_url . '/user/'.$user->uid.'/edit'; 
		$form['field_id_proof_of_authorized']['#suffix'] = '<a class="change-pass" href="'.$userlink.'">Change Password</a>';
 	}

 	if($form_id == 'user_login_block' || $form_id == 'user_login'){
 		$form['actions']['submit']['#value'] = 'Login';
 		$form['remember_me']['#title'] = 'Remember Me';
 	}
 	if($form_id == 'user_register_form'){
 		$form['actions']['submit']['#value'] = 'Register Now';
 		$form['account']['mail']['#title'] = 'Email';
 	}
 	if($form_id == 'webform_client_form_5') {
 		$form['actions']['submit']['#value'] = 'Submit';
 	}
 	if($form_id == 'webform_client_form_61'){
 		if(isset($_REQUEST['nid']) && !empty($_REQUEST['nid'])) {
 			$node_info = node_load($_REQUEST['nid']);
 			$form['submitted']['commodity']['#webform_component']['value'] = $node_info->title;
 			$form['submitted']['commodity']['#default_value'] = $node_info->title;
 			if(isset($node_info->field_total_quantity[LANGUAGE_NONE]) && !empty($node_info->field_total_quantity[LANGUAGE_NONE])) {
 				$form['submitted']['qty']['#webform_component']['value'] = $node_info->field_total_quantity[LANGUAGE_NONE][0]['value'];
 				$form['submitted']['qty']['#default_value'] = $node_info->field_total_quantity[LANGUAGE_NONE][0]['value'];
 			}

 			if(isset($node_info->field_load_port[LANGUAGE_NONE]) && !empty($node_info->field_total_quantity[LANGUAGE_NONE])) {
 				$form['submitted']['load_port']['#webform_component']['value'] = $node_info->field_load_port[LANGUAGE_NONE][0]['value'];
 				$form['submitted']['load_port']['#default_value'] = $node_info->field_load_port[LANGUAGE_NONE][0]['value'];
 			}
 		}
 	}
}
