<?php

/**
 * @file
 * Main file for the Etrade miscellaneous module, which containg logics for adding or alter node related functionality.
 * 
 * @ingroup etrade_misc
 */


function etrade_misc_menu() {
  $items['order-accept/%/%'] = array(
	  'title' => t('Accept Order'),
		'description' => 'User will accept order if he is intrested',
		'page arguments' => array(1,2),
		'page callback' => 'etrade_order_accept',
		'access arguments' => array('access content'),
  );

  return $items;
}

function etrade_order_accept($arg1, $arg2){

  global $user;
  global $base_url;
 
  $another_user = $user->uid;
  $node_info = node_load($arg1);
  $node_info->field_another_user[LANGUAGE_NONE][0]['value'] = $another_user;
  
  $node_info = node_save($node_info);
  	
	//check if order is accepted through API or website
	if (isset($_GET['api']) && $_GET['api'] == 'Y') {
	  $result['status'] = '200'; 
	  $result['message'] = 'success'; 
	  print(json_encode($result)); exit;
	}
	else {

	  if($arg2 == 0){
			$redirect = 'trade-details';
	  }
	  else{
	    $redirect = 'trade-details?page='. $arg2;
	  }

	  drupal_goto($redirect);
	  drupal_set_message("Your request for order has been sent successfully");
	} 
}

function etrade_misc_node_presave($node){
	/*global $user;
	if($node->type == 'user_profile'){
		$user = user_load($user->uid);
		if(in_array('administrator', $user->roles) || in_array('Manager', $user->roles)) {
			return true;
		}
		else{
			if(in_array('authenticated user', $user->roles)){
				if(!empty($node->field_company_name[LANGUAGE_NONE]) && !empty($node->field_company_type[LANGUAGE_NONE]) && !empty($node->field_address_company[LANGUAGE_NONE]) && !empty($node->field_state[LANGUAGE_NONE]) && !empty($node->field_landline_no_of_company[LANGUAGE_NONE]) && !empty($node->field_tax_registration_no_[LANGUAGE_NONE]) && !empty($node->field_authorized_person[LANGUAGE_NONE]) && !empty($node->field_address_of_authorized_pers[LANGUAGE_NONE]) && !empty($node->field_phone_number[LANGUAGE_NONE]) && !empty($node->field_email_address[LANGUAGE_NONE]) && !empty($node->field_state[LANGUAGE_NONE][0]['city']) && !empty($node->field_state[LANGUAGE_NONE][0]['province']) && !empty($node->field_state[LANGUAGE_NONE][0]['country']) && !empty($node->field_state[LANGUAGE_NONE][0]['postal_code']) && (!empty($node->field_registration_certificate[LANGUAGE_NONE]) || !empty($node->field_address_proof_of_company[LANGUAGE_NONE]) || !empty($node->field_id_proof_of_authorized[LANGUAGE_NONE]))) {	
					$user->field_profile_status1[LANGUAGE_NONE][0]['value'] = 1;
					user_save($user);
					}
				else {
					$user->field_profile_status1[LANGUAGE_NONE][0]['value'] = 0;
					user_save($user);	
				}
			}
		}
	}*/
}

function etrade_misc_form_alter(&$form, &$form_state, $form_id) {	
	global $user;
	global $base_url;
	if($form_id == 'user_profile_node_form'){
		$userlink = $base_url . '/user/'.$user->uid.'/edit'; 
		$form['field_id_proof_of_authorized']['#suffix'] = '<a class="change-pass" href="'.$userlink.'">Change Password</a>';
 	}

 	if($form_id == 'user_login_block' || $form_id == 'user_login'){
 		$form['actions']['submit']['#value'] = 'Login';
 		$form['remember_me']['#title'] = 'Remember Me';
 	}
 	if($form_id == 'user_register_form'){
 		$form['actions']['submit']['#value'] = 'Register Now';
 		$form['account']['mail']['#title'] = 'Email';
 	}
 	if($form_id == 'webform_client_form_5') {
 		$form['actions']['submit']['#value'] = 'Submit';
 	}
 	if($form_id == 'webform_client_form_61'){
 		if(isset($_REQUEST['nid']) && !empty($_REQUEST['nid'])) {
 			$node_info = node_load($_REQUEST['nid']);
 			$form['submitted']['commodity']['#webform_component']['value'] = $node_info->title;
 			$form['submitted']['commodity']['#default_value'] = $node_info->title;
 			if(isset($node_info->field_total_quantity[LANGUAGE_NONE]) && !empty($node_info->field_total_quantity[LANGUAGE_NONE])) {
 				$form['submitted']['qty']['#webform_component']['value'] = $node_info->field_total_quantity[LANGUAGE_NONE][0]['value'];
 				$form['submitted']['qty']['#default_value'] = $node_info->field_total_quantity[LANGUAGE_NONE][0]['value'];
 			}

 			if(isset($node_info->field_load_port[LANGUAGE_NONE]) && !empty($node_info->field_total_quantity[LANGUAGE_NONE])) {
 				$form['submitted']['load_port']['#webform_component']['value'] = $node_info->field_load_port[LANGUAGE_NONE][0]['value'];
 				$form['submitted']['load_port']['#default_value'] = $node_info->field_load_port[LANGUAGE_NONE][0]['value'];
 			}
 		}
 	}
}


/**
 * To alter commodity-node-form form 
 */
function etrade_misc_form_commodity_node_form_alter(&$form, $form_state, $form_id) {
	
	$node = $form_state['node'];

	// alter form on form updation
	if (isset($node->nid)) {		
		$form['field_another_user']['#access'] = FALSE;

		$buyer = "";
		$seller = "";

		if(isset($node->field_commodity_type[LANGUAGE_NONE]) && !empty($node->field_commodity_type[LANGUAGE_NONE])){

			//comodity 0 means buyes and 1 means seller
	        if($node->field_commodity_type[LANGUAGE_NONE][0]['value'] == 0) {	            
	            $buyer_info = user_load($node->uid);
		        $seller_info = user_load($node->field_another_user[LANGUAGE_NONE][0]['value']);
		        $buyer = $buyer_info->name;
		        $seller = $seller_info->name;
	        }
	        else {
	            $buyer_info = user_load($node->field_another_user[LANGUAGE_NONE][0]['value']);
		        $seller_info = user_load($node->uid);
		        $buyer = $buyer_info->name;
		        $seller = $seller_info->name;
	        }
	    }

		/*$form['seller'] = array(
	      '#type' => 'textfield',
	      '#title' => t('Seller Name'),
		  '#default_value' => $seller,
		  '#weight' => 2,
		  '#attributes' => array('readonly' => 'readonly'),
		  '#prefix' => '<div class="group-user-profile-right">', '#suffix' => '</div>',
	    );

	    $form['buyer'] = array(
	      '#type' => 'textfield',
	      '#title' => t('Buyer Name'),
		  '#default_value' => $buyer,
		  '#weight' => 2,
		  '#attributes' => array('readonly' => 'readonly'),
		  '#prefix' => '<div class="group-user-profile-right">', '#suffix' => '</div>',
	    ); */

	    $form['field_buyer_commission']['#prefix'] = '<div class="buyer-name"> <span>Buyer Name:</span>' . $buyer . '</div>';
	    $form['field_buyer_commission']['#prefix'] .= '<div class="seller-name"> <span>Seller Name:</span>' . $seller . '</div>';
	    
	}
} 

function etrade_misc_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if($form['#form_id'] == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-countrywise-commodities-block-1'){
    $form['field_commodity_type_value']['#options'][0] = 'Buy Order';
    $form['field_commodity_type_value']['#options'][1] = 'Sell Order';
  }  
}

function etrade_misc_views_query_alter(&$view, &$query) {
	global $user;
	if($view->name == 'user_order_acceptance_details') {
	    $query->where['2']['conditions']['0']['value'] = $user->uid;
	    $query->where['2']['conditions']['1']['value'][0] = $user->uid;
	}

	// to alter query for trade orders views services
	if(($view->name == 'orders') && (($view->current_display == 'services_3') || ($view->current_display == 'services_4'))) {
	    $query->where['2']['conditions']['0']['value'] = $user->uid;
	    $query->where['2']['conditions']['1']['value'][0] = $user->uid;
	}

}

